/*
 * battery_adc.h
 *
 *  Created on: 03.03.2026
 *      Author: FI
 */

#pragma once

#include <stdint.h>
#include <stdbool.h>
#include "stm32l4xx_hal.h"

/**
 * Battery monitor using gated divider via SIP32431 load-switch.
 *
 * Hardware assumptions (from your project):
 * - BAT_MON_Pin enables the SIP32431 (active high).
 * - ADC1 regular channel configured to read PA0 (ADC1_IN5).
 * - Divider: Rtop=10k (to BAT_MON), Rbot=49.9k (to GND), ADC at midpoint.
 *
 * Vadc = Vbat * (Rbot / (Rtop + Rbot))
 * Vbat = Vadc * ((Rtop + Rbot) / Rbot)
 */

/* ---- User-tunable defaults ---- */

/* Divider values in ohms */
#ifndef BAT_ADC_RTOP_OHMS
#define BAT_ADC_RTOP_OHMS        (10000.0f)
#endif

#ifndef BAT_ADC_RBOT_OHMS
#define BAT_ADC_RBOT_OHMS        (49900.0f)
#endif

/* Delay after enabling BAT_MON to allow RC settle (ms).
 * With 100nF at BAT_MON and ~60k path, tau ~ 6ms, so 30ms is very safe.
 */
#ifndef BAT_ADC_SETTLE_MS
#define BAT_ADC_SETTLE_MS        (30u)
#endif

/* Number of averaged samples */
#ifndef BAT_ADC_SAMPLES
#define BAT_ADC_SAMPLES          (8u)
#endif

/* Timeout for PollForConversion (ms) */
#ifndef BAT_ADC_POLL_TIMEOUT_MS
#define BAT_ADC_POLL_TIMEOUT_MS  (10u)
#endif

/* ---- API ---- */

/**
 * Initialize battery monitor module.
 * Pass the ADC handle generated by Cube (usually &hadc1).
 */
void BAT_ADC_Init(ADC_HandleTypeDef *hadc);

/**
 * Read battery voltage (mV).
 *
 * @param[out] out_raw_avg Optional. If non-NULL, returns averaged raw ADC (0..4095).
 * @return Battery voltage in millivolts. Returns 0 on failure.
 */
uint32_t BAT_ADC_Read_mV(uint16_t *out_raw_avg);

/**
 * Optional helper: read ADC node voltage in mV (post-divider).
 * Useful for debug.
 */
uint32_t BAT_ADC_ReadNode_mV(uint16_t *out_raw_avg);

/**
 * Optional: set VDDA used for conversion (mV).
 * If you later implement VREFINT-based VDDA measurement, call this.
 * Default is 3300mV.
 */
void BAT_ADC_SetVDDA_mV(uint32_t vdda_mV);
